#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Secrets captured this run land in .env.ops-wizard (git-ignored) so the
# wizard can be re-run without re-pasting; CI values go to GitHub secrets.
ENV_FILE="${ENV_FILE:-.env.ops-wizard}"

TOTAL_STAGES=9

banner "TechStore go-live: secrets + backup chứng minh"

say "Wizard này gán 6 secrets GitHub (monitor/alert/backup chạy được ngay),"
say "gán env Vercel qua CLI, và kết thúc bằng backup production chạy thật."
note "Xem trước: docs/ops/BACKLOG.md §A + §E, docs/ops/DEPLOY.md."

# ── Stage 1: CRON_SECRET (sinh máy) ───────────────────────────────────────
stage "Sinh CRON_SECRET"
say "Giá trị này guard /api/cron/* ở Vercel và cho workflow Monitor gọi vào."
say "Wizard sinh ngẫu nhiên — bạn không phải tự nghĩ."
confirm "Sinh CRON_SECRET mới (32 byte hex) và ghi vào .env.ops-wizard?" || true
if [[ -z "${CRON_SECRET:-}" ]]; then
  CRON_SECRET=$(openssl rand -hex 32)
fi
printf '  %s✓ đã sinh:%s CRON_SECRET (64 ký tự hex)%s\n' "$GREEN" "$RESET" "$DIM"
write_env CRON_SECRET "$CRON_SECRET"
set_secret CRON_SECRET "$CRON_SECRET"

# ── Stage 2: Supabase DB URL ──────────────────────────────────────────────
stage "Supabase — connection string DB"
say "Cần chuỗi postgres của project production (backup dump + drift check)."
open_url "https://supabase.com/dashboard"
step "Chọn project Supabase production của TechStore."
step "Project Settings → Database → Connection string → tab 'URI'."
step "Chọn database password của project, copy chuỗi bắt đầu bằng postgresql://"
ask_secret SUPABASE_DB_URL "Paste chuỗi postgresql:// (postgres:...@db.<ref>.supabase.co:5432/postgres):"
write_env SUPABASE_DB_URL "$SUPABASE_DB_URL"
set_secret SUPABASE_DB_URL "$SUPABASE_DB_URL"
note "Chuỗi này chứa password DB — chỉ nằm ở .env.ops-wizard (đã git-ignore) và GitHub secret."

# ── Stage 3: Supabase service_role key ────────────────────────────────────
stage "Supabase — service_role key"
say "Dùng bởi workflow Backup để upload file backup lên Storage bucket 'backups'."
open_url "https://supabase.com/dashboard"
step "Cùng project → Project Settings → API."
step "Mục 'Project API keys' → hàng service_role → Reveal → copy."
ask_secret SUPABASE_SERVICE_ROLE_KEY "Paste service_role key (eyJhbGci...):"
write_env SUPABASE_SERVICE_ROLE_KEY "$SUPABASE_SERVICE_ROLE_KEY"
set_secret SUPABASE_SERVICE_ROLE_KEY "$SUPABASE_SERVICE_ROLE_KEY"

# ── Stage 4: Vercel env (production) ───────────────────────────────────────
stage "Vercel — env production cho app"
say "App trên Vercel cần CRON_SECRET trùng GitHub secret (Monitor gọi được cron)."
say "Wizard tự gán qua 'vercel env add' nếu bạn đã login CLI; không thì ghi checklist tay."
confirm "Đã cài Vercel CLI (npm i -g vercel) và login (vercel login)?" || true
if command -v vercel >/dev/null 2>&1; then
  if printf '%s' "$CRON_SECRET" | vercel env add CRON_SECRET production >/dev/null 2>&1; then
    printf '  %s✓ set%s Vercel env CRON_SECRET (production)%s\n' "$GREEN" "$RESET" "$DIM"
  else
    warn "không gán được Vercel env (chưa link project?) — làm tay ở Stage 5"
    SKIPPED+=("Vercel env CRON_SECRET (dashboard: Project → Settings → Environment Variables)")
  fi
else
  warn "Vercel CLI chưa cài — Stage 5 sẽ hướng dẫn gán tay"
  SKIPPED+=("Vercel env CRON_SECRET (dashboard: Project → Settings → Environment Variables)")
fi
note "Nếu NEXT_PUBLIC_SUPABASE_URL / keys / SUPABASE_SERVICE_ROLE_KEY chưa có ở Vercel, gán theo docs/ops/DEPLOY.md §2."

# ── Stage 5: PROD_BASE_URL sau deploy đầu ─────────────────────────────────
stage "PROD_BASE_URL — URL production sau deploy đầu"
say "Monitor cần URL thật để ping /api/health + storefront mỗi 15 phút."
say "Nếu bạn chưa deploy lần nào: chạy theo docs/ops/DEPLOY.md rồi quay lại wizard này."
step "Mở Vercel dashboard → project TechStore → copy production URL (https://…vercel.app hoặc domain riêng)."
open_url "https://vercel.com/dashboard"
ask PROD_BASE_URL "Paste URL production (https://…):"
write_env PROD_BASE_URL "$PROD_BASE_URL"
set_secret PROD_BASE_URL "$PROD_BASE_URL"
if command -v curl >/dev/null 2>&1 && [[ -n "${PROD_BASE_URL:-}" ]]; then
  code=$(curl -sS -o /dev/null -w '%{http_code}' --max-time 15 "$PROD_BASE_URL/api/health" || true)
  if [[ "$code" = "200" ]]; then
    printf '  %s✓ /api/health trả 200 — deployment đang sống%s\n' "$GREEN" "$RESET"
  else
    warn "/api/health trả '$code' — deploy chưa lên hoặc URL sai; quay lại stage này sau."
  fi
fi

# ── Stage 6: Telegram alert ──────────────────────────────────────────────
stage "Telegram — bot cảnh báo"
say "Workflow Alert-on-failure nhắn Telegram khi CI/Backup/Monitor đỏ trên main."
open_url "https://t.me/BotFather"
step "Nhấn Start, gửi /newbot, đặt tên + username (phải kết thúc bằng 'bot')."
step "BotFather trả 'token' — copy nguyên dòng (dạng 123456:ABC-…)."
ask_secret TELEGRAM_BOT_TOKEN "Paste bot token:"
step "Mở chat với bot mới của bạn, nhấn Start, gửi '/start'."
step "Mở chat với @userinfobot, nhấn Start — nó hiển thị 'Id' của bạn (số)."
open_url "https://t.me/userinfobot"
ask TELEGRAM_CHAT_ID "Id của bạn (con số):"
write_env TELEGRAM_BOT_TOKEN "$TELEGRAM_BOT_TOKEN"
write_env TELEGRAM_CHAT_ID "$TELEGRAM_CHAT_ID"
set_secret TELEGRAM_BOT_TOKEN "$TELEGRAM_BOT_TOKEN"
set_secret TELEGRAM_CHAT_ID "$TELEGRAM_CHAT_ID"
say "Kiểm tra nhanh bot gửi được không:"
if response=$(curl -sS -w '\n%{http_code}' --max-time 15 -X POST \
  "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
  --data-urlencode "chat_id=${TELEGRAM_CHAT_ID}" \
  --data-urlencode "text=TechStore alert test — wizard go-live" 2>/dev/null) \
  && [[ "$(tail -n1 <<<"$response")" = "200" ]]; then
  printf '  %s✓ Telegram nhận được test message — check điện thoại của bạn%s\n' "$GREEN" "$RESET"
else
  warn "Telegram chưa gửi được — kiểm tra token/chat id (bot phải được /start trước)."
fi

# ── Stage 7: Backup chạy thật 1 lần (chứng minh) ───────────────────────────
stage "Chạy backup production thật 1 lần"
say "Đây là bước quan trọng nhất: chứng minh pipeline backup end-to-end —"
say "dump → upload Storage → restore vào Postgres scratch → so khớp row count."
step "Nhấn Enter để wizard trigger workflow Backup qua gh CLI."
pause
if gh workflow run backup.yml --ref main 2>/dev/null; then
  sleep 8
  run_url=$(gh run list --workflow=backup.yml --limit 1 --json url --jq '.[0].url' 2>/dev/null || true)
  open_url "${run_url:-https://github.com/H-Thanh0603/Tech_store/actions/workflows/backup.yml}"
  say "Chờ run xanh (≈2–4 phút). Nếu đỏ, mở log step đầu tiên — thường là"
  say "SUPABASE_DB_URL sai định dạng (phải là postgresql://…@db.<ref>.supabase.co…)."
  if ! confirm "Workflow Backup đã pass (xanh)?"; then
    SKIPPED+=("Backup run đầu chưa xanh — xem lại secrets Stage 2/3")
  fi
else
  warn "không trigger được (gh chưa auth?) — mở URL trên, nhấn nút 'Run workflow'."
fi

# ── Stage 8: Monitor + verify tự động ──────────────────────────────────────
stage "Chạy Monitor 1 lần + verify secrets còn lại"
step "Wizard trigger workflow Monitor (ping health + drift check)."
pause
if gh workflow run monitor.yml --ref main 2>/dev/null; then
  sleep 8
  run_url=$(gh run list --workflow=monitor.yml --limit 1 --json url --jq '.[0].url' 2>/dev/null || true)
  open_url "${run_url:-https://github.com/H-Thanh0603/Tech_store/actions/workflows/monitor.yml}"
  if ! confirm "Workflow Monitor đã pass?"; then
    SKIPPED+=("Monitor chưa xanh — xem PROD_BASE_URL/CRON_SECRET/SUPABASE_DB_URL")
  fi
else
  warn "không trigger được — mở URL trên, nhấn 'Run workflow'."
fi

# ── Stage 9: Việc chỉ bạn làm được — checklist tài khoản ───────────────────
stage "Checklist tài khoản (tự làm khi rảnh)"
say "6 secrets đã xong. Còn các việc owner trong docs/ops/BACKLOG.md §E:"
step "Mua domain + Cloudflare — docs/ops/CLOUDFLARE_SETUP.md (30 phút)."
step "VNPay merchant thật thay sandbox: merchant.vnpayment.vn đăng ký, nhận tmn_code + secret thật, đổi return/IPN URL sang domain thật, gán VNPAY_TMN_CODE + VNPAY_SECRET ở Vercel, gỡ VNP_URL sandbox."
step "Bật 2FA: GitHub, Vercel, Supabase, Resend/Sentry, VNPay."
step "GitHub repo → Settings → Branches → add rule main: require PR + status checks CI."
step "Resend: verify domain, đổi EMAIL_FROM sang địa chỉ domain mình."
step "Sentry project + SENTRY_DSN nếu muốn error tracking (không bắt buộc)."
note "Wizard này chỉ nên chạy 1 lần; file .env.ops-wizard chứa secret — KHÔNG commit."
pause "Hoàn tất — nhấn Enter xem tổng kết"

finish
